"""initial schema

Revision ID: f3dcac284332
Revises: 
Create Date: 2025-12-06 04:42:04.827000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dcac284332'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('avg_pe_ratio', sa.Float(), nullable=True),
    sa.Column('avg_revenue_growth', sa.Float(), nullable=True),
    sa.Column('sum_revenue', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_stats_id'), 'industry_stats', ['id'], unique=False)
    op.create_index(op.f('ix_industry_stats_industry'), 'industry_stats', ['industry'], unique=False)
    op.create_table('industry_stats_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('avg_pe_ratio', sa.Float(), nullable=True),
    sa.Column('avg_revenue_growth', sa.Float(), nullable=True),
    sa.Column('sum_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_stats_history_id'), 'industry_stats_history', ['id'], unique=False)
    op.create_index(op.f('ix_industry_stats_history_industry'), 'industry_stats_history', ['industry'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_id'), 'tickers', ['id'], unique=False)
    op.create_index(op.f('ix_tickers_industry'), 'tickers', ['industry'], unique=False)
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('ticker_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('net_income_ttm', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('latest_revenue', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_stats_id'), 'ticker_stats', ['id'], unique=False)
    op.create_index(op.f('ix_ticker_stats_ticker_id'), 'ticker_stats', ['ticker_id'], unique=False)
    op.create_table('ticker_stats_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('net_income_ttm', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('latest_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_stats_history_id'), 'ticker_stats_history', ['id'], unique=False)
    op.create_index(op.f('ix_ticker_stats_history_ticker_id'), 'ticker_stats_history', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_stats_history_ticker_id'), table_name='ticker_stats_history')
    op.drop_index(op.f('ix_ticker_stats_history_id'), table_name='ticker_stats_history')
    op.drop_table('ticker_stats_history')
    op.drop_index(op.f('ix_ticker_stats_ticker_id'), table_name='ticker_stats')
    op.drop_index(op.f('ix_ticker_stats_id'), table_name='ticker_stats')
    op.drop_table('ticker_stats')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_industry'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_id'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_industry_stats_history_industry'), table_name='industry_stats_history')
    op.drop_index(op.f('ix_industry_stats_history_id'), table_name='industry_stats_history')
    op.drop_table('industry_stats_history')
    op.drop_index(op.f('ix_industry_stats_industry'), table_name='industry_stats')
    op.drop_index(op.f('ix_industry_stats_id'), table_name='industry_stats')
    op.drop_table('industry_stats')
    # ### end Alembic commands ###
